language: node_js
node_js:
    - 6.10
install:
    - npm install grunt@1.0.1
    - npm install
script:
    - ./node_modules/.bin/grunt initial
before_deploy:
    - openssl aes-256-cbc -K $encrypted_6dbc9dbe3b2a_key -iv $encrypted_6dbc9dbe3b2a_iv -in deploy/key.enc -out deploy/key -d
    - node_modules/.bin/grunt dev build
deploy:
    provider: script
    script: deploy/deploy.sh
    skip_cleanup: true
    on:
        branch: github.io
notifications:
    email:
        recipients:
            - cnspeckn@googlemail.com
