language: node_js
node_js:
  - lts/*
script:
  - yarn test
  - yarn build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_6dbc9dbe3b2a_key -iv $encrypted_6dbc9dbe3b2a_iv -in deploy/key.enc -out deploy/key -d
deploy:
  - provider: script
    script: deploy/deploy_github_io.sh
    skip_cleanup: true
    on:
      tags: true
