language: node_js
node_js:
    - 7
cache:
    yarn: true
before-script:
    - yarn add grunt
    - yarn add grunt-cli
    - yarn install
script:
    - grunt initial
before_deploy:
    - openssl aes-256-cbc -K $encrypted_6dbc9dbe3b2a_key -iv $encrypted_6dbc9dbe3b2a_iv -in deploy/key.enc -out deploy/key -d
    - grunt dev build
    - grunt dev
deploy:
    provider: script
    script: deploy/deploy.sh
    skip_cleanup: true
    on:
        branch: github.io
notifications:
    email:
        recipients:
            - cnspeckn@googlemail.com
