name: Build and run tests
on:
  push:
    branches-ignore:
      - legacy
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn build
      - run: yarn test
